version: '3.8'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    ports:
      - "5432:5432"


  spring-backend:
    build:
      context: ./backend
      dockerfile: ./docker/spring/Dockerfile
    ports:
      - "8080:8080"


#  nginx-frontend:
#    build:
#      context: ./frontend
#      dockerfile: ./docker/nginx/Dockerfile
#    ports:
#      - "80:80"

#  angular-frontend:
#    build:
#      context: ./frontend
#      dockerfile: ./docker/angular/Dockerfile
#    ports:
#      - "4200:80"