version: '3.8'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
    ports:
      - "5432:5432"
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"


  spring-backend:
    build:
      context: ./backend
      dockerfile: ./docker/spring/Dockerfile
    ports:
      - "8080:8080"


  angular-frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/angular/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - spring-backend
#    volumes:
#      - ./logs/nginx:/var/log/nginx